### ISSUE TITLE
 Cross-Origin Request Blocked Error

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [akhenry/openmct-yamcs#100]
Hi there,

I was trying to run the project as per the instructions on the README and I get the following errors in
![Screenshot from 2022-02-02 11-27-24](https://user-images.githubusercontent.com/68551873/152205742-bd82578b-d432-4762-8058-5e87227d7d6c.png)
 

I was using the quickstart project from YAMCS.

I researched and I tried to add the following to webpack config:

```
     headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept'
    }
```
After adding that, still have the same problem.

Here is some info about my environment:

```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

NODE=v12.22.9
npm=6.14.15
Firefox=96.0
```

**Comment by akhenry** [comment]
Sorry this isn't working for you. The URLs in the error messages don't look right, the example application uses a local proxy to bypass CORS, but from your error message it appears to be trying to access Yamcs directly.

We have made some changes to the build process for the example application recently. Would you mind pulling down the latest version of this repository and following [the updated instructions](https://github.com/akhenry/openmct-yamcs/blob/master/README.md#installation)? Thanks!

**Comment by unlikelyzero** [comment]
@lorenzo-gomez-windhover any update? Would you mind trying again on Chrome?

**Comment by unlikelyzero** [comment]
@lorenzo-gomez-windhover please let us know if you can reproduce this!
