### ISSUE TITLE
Remove NonEditableFolder Plugin

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#113]
**Is your feature request related to a problem? Please describe.**
No longer needed.

**Describe the solution you'd like**
Removed.

**Describe alternatives you've considered**
Not removing it.

**Additional context**
Directly related to:
https://github.com/nasa/openmct/issues/4899
https://github.com/nasa/openmct/issues/4323
https://github.com/nasa/openmct/issues/3741

## Testing
- on previous noneditable folder types, "VIPER" (and child folders) and "VIPER Plans", check you cannot edit or modify
- you SHOULD be able to still link these items

**Comment by unlikelyzero** [comment]
# Testing Notes
on previous noneditable folder types, "VIPER" (and child folders) and "VIPER Plans", check you cannot edit or modify
you SHOULD be able to still link these items

**Comment by nikhilmandlik** [comment]
Verified Fixed.
