### ISSUE TITLE
Indicate parameter data is stale in OpenMCT when parameter acquisition status from yamcs is "expired"

### ISSUE THREAD

**Issue by AdamElliott-AB** [akhenry/openmct-yamcs#116]
**Is your feature request related to a problem? Please describe.**
We want OpenMCT views of parameters (such as LAD tables) to indicate if parameter data is stale. This "staleness" information is already available in Yamcs.

**Describe the solution you'd like**
When subscribing to parameter updates from yamcs, openmct-yamcs could request updateOnExpiration. If ParameterValue data returned from yamcs has acquisitionStatus = 'EXPIRED', then the staleness should be indicated wherever that data is displayed in OpenMCT views. I expect OpenMCT already has a way to indicate this status. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jvigliotta** [comment]
@akhenry let's talk about this when you get back

**Comment by akhenry** [comment]
This seems like a job for the "limit" evaluators, which should maybe be recast as "telemetry status" evaluators. In any case, they evaluate telemetry data and spit out a CSS class to apply wherever the telemetry is shown, so I think we could use it for indicating staleness. We would need to figure out how to "update" existing values in the view if their status _changes_ to stale. I expect that Yamcs re-emits the parameter value when it goes stale, so it _should_ work just fine, without having to make any changes to our views, however it's possible that we are making assumptions in some places that new values always have timestamps that are later than the last value.

@AdamElliott-AB We will put this into consideration for a release in the second half of CY2022. If you need something sooner we can provide some guidance on the code changes needed.

**Comment by akhenry** [comment]
@AdamElliott-AB Staleness is on the board for our next two sprints.

**Comment by AdamElliott-AB** [comment]
Awesome!

**Comment by jvigliotta** [comment]
## Testing Notes
- coming soon!

**Comment by ozyx** [comment]
Verified fixed Testathon 02-02-2023

**Comment by unlikelyzero** [comment]
@scottbell to retest on local deployment

**Comment by scottbell** [comment]
Worked well with YAMCS data going to `EXPIRED` every half second or so:
https://user-images.githubusercontent.com/9853862/216635412-3fd8b446-8a21-4b96-892a-9aa74e9b1a06.mov

@jvigliotta only issues I found were:

- Same as @ozyx found, overlay plots in stacked plots weren't displaying staleness
- ConditionSets weren't showing staleness in DisplayLayouts.

**Comment by jvigliotta** [comment]
@scottbell thanks! I've addressed these in Open MCT. For Condition Sets, you have to specifically set up the `isStale` condition. When looking at/editing the condition set, you will see staleness if if has stale telemetry, but it won't do so in display layouts unless you specify staleness as a condition.
