### ISSUE TITLE
Update Paths and Open MCT Dependency versions

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#117]
#### Summary

Currently unable to use YAMCS with Quickstart. The rewrite paths for the proxy settings in webpack are missing slashes, this causes the websockets and historical api pathes to be broken. Also, the latest version of Open MCT served by NPM is too old to work with the latest version of openmc-yamcs, we'll need to temporarily set it to 1.8.4 until it's updated on NPM.

#### Expected vs Current Behavior

It should work.

#### Impact Check List
 

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Follow the instructions in this repo to bring up YAMCS and Quickstart
2. It won't start due to errors

#### Additional Information

Not sure how long this has been broken, but the YAMCS/Quickstart combo is unusable until this is fixed.

**Comment by michaelrogers** [comment]
Fix verified during testathon on 2022-03-14. Tested locally by cloning the quickstart and openmct-yamcs repos.
