### ISSUE TITLE
Use `generationTime` instead of `generationTimeUTC`

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#126]
#### Summary
Yamcs deprecated the use of `generationTimeUTC` and removed it completely in a recent version of 
Yamcs.

We stopped using `generationTime` because it was previously a number in UNIX epoch that did not include leap seconds. `generationTime` is now an ISO compliant string that can be natively parsed to a JavaScript date so we should just use that instead.

**Comment by unlikelyzero** [comment]
### Testing Instructions
Verify the following
- Local Clock start and stop bounds can be adjusted on a Telemetry Object View from YAMCS
- Fixed Timespan bounds can be adjust on a Telemetry Object View from YAMCS
- Fixed Timespan bounds can be adjust on a Telemetry Object View embedded within a Display Layout from YAMCS
- Fixed Timespan bounds can be adjust on a Telemetry Imagery Object embedded within a Display Layout from YAMCS
- Local Timespan bounds can be adjust on a Telemetry Imagery Object embedded within a Display Layout from YAMCS

**Comment by akhenry** [comment]
### Additional Testing Instructions!
1. Verify that timestamps are populated in the table view of telemetry
2. Verify that plots show historical and real-time data
3. Verify that LAD tables are showing real-time data
4. Verify that display layouts show alpha-numeric telemetry values (ie. the default view for telemetry when you drag it into a display layout)

**Comment by ozyx** [comment]
Verified Testathon 7/8/22

Verified every case listed above
