### ISSUE TITLE
[User Endpoint] Need to specify user endpoint for use with quickstart

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#130]
#### Summary

Need to specify a user endpoint for example use with quickstart.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by ozyx** [comment]
Verified Testathon 7/8/22:

https://github.com/akhenry/openmct-yamcs/pull/131/files#diff-11905e05b9e7ab41be0595547d67677c1d4ee0d388aeb0cc76db9a423f04a33eR8
