### ISSUE TITLE
Do not use the parameter archive for `latest` type requests in real-time mode.

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#139]
**Is your feature request related to a problem? Please describe.**
Currently we use the parameter archive API endpoint with a size of 1 to request the latest values for parameters. This works, however it results in a very large number of requests that in real-time mode are now redundant due to [a recent change](https://github.com/akhenry/openmct-yamcs/pull/133/files#diff-c120fce88cd7184750d4a270bc39cba07b2fb7638f8da68333289639b948f5cdR38).

* Note that if the user **is not** in real-time mode we should still use the parameter archive.

**Comment by akhenry** [comment]
To be clear, in real-time mode, it is no longer necessary to query the parameter archive at all. When we establish a websocket connection we automatically get the latest value for each parameter.

**Comment by scottbell** [comment]
@akhenry to check with @shefalijoshi about independent time conductors. @akhenry's think if we add the `mode` to the `options` (e.g., `fixed` or `realtime`)

**Comment by akhenry** [comment]
OK, here's how I think we should approach this:
1. Modify `TelemetryAPI.request` to support _optionally_ providing a time context in the options object. (Probably no code change needed to support this since options are just passed through? Just update the docs)
2. Modify `TelemetryAPI.standardizeRequestOptions` (and make it private while we're at it) to default the `timeContext` option to the global time context (ie. `openmct.time`) if none was provided.
3. Modify the TimeContext class to add an `isRealtime()` function that, for now, returns true if there is a clock set on the time context. This will be inherited by both global and independent time contexts.
4. Modify the realtime provider to check if the request has the `latest` strategy _and_ the provided time context is in realtime mode.

My reasoning for this approach is that every other one that I could think of had edge cases that were undesirable. Adding time context awareness to the telemetry API is also needed [to address this issue](https://github.com/nasa/openmct/issues/4285).

**Comment by scottbell** [comment]
@akhenry Sound approach. I'm on it.

**Comment by scottbell** [comment]
@akhenry I've got two branches attached this to this ticket, and I'm able to see check this new option [within the historical telemetry provider](https://github.com/akhenry/openmct-yamcs/blob/139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode/src/providers/historical-telemetry-provider.js#L57).

However, the way I'm asking for the TimeContext [in the LAD row](https://github.com/nasa/openmct/compare/master...139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1#diff-c81b5971bfc1744860f666d448e5be2aac414b8e60d5f3e6e75f5fdc8b8fdfd7R116) and [the TelemetryView](https://github.com/nasa/openmct/compare/master...139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1#diff-db974065ad1253965c498e3a382990e3f0917626353fcbe97dfda23072606c48R284) may not be correct. Both views are returning an [IndependentTimeContext](https://github.com/nasa/openmct/blob/139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1/src/api/time/IndependentTimeContext.js) here, which I don't think is right as the the [activeClock](https://github.com/nasa/openmct/blob/139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1/src/api/time/TimeContext.js#L372) is always `null`.

I'll keep investigating.

**Comment by akhenry** [comment]
> However, the way I'm asking for the TimeContext [in the LAD row](https://github.com/nasa/openmct/compare/master...139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1#diff-c81b5971bfc1744860f666d448e5be2aac414b8e60d5f3e6e75f5fdc8b8fdfd7R116) and [the TelemetryView](https://github.com/nasa/openmct/compare/master...139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1#diff-db974065ad1253965c498e3a382990e3f0917626353fcbe97dfda23072606c48R284) may not be correct. Both views are returning an [IndependentTimeContext](https://github.com/nasa/openmct/blob/139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1/src/api/time/IndependentTimeContext.js) here, which I don't think is right as the the [activeClock](https://github.com/nasa/openmct/blob/139-do-not-use-the-parameter-archive-for-latest-type-requests-in-real-time-mode-1/src/api/time/TimeContext.js#L372) is always null.

So I _think_ the correct behavior of `openmct.time.getContextForView` is to _always_ return an independent time context. In the case that the view is just tracking the global time context, then that independent time context will just be locked to the global time context.

If the clock is _always_ null in that case, it might be a bug in our Time API.

**Comment by scottbell** [comment]
Talking with @ozyx, it sounds like a workaround would be to pass and empty array instead of the actual object path. In that case, it returns a global time context, which has a clock set.

**Comment by ozyx** [comment]
> Talking with @ozyx, it sounds like a workaround would be to pass and empty array instead of the actual object path. In that case, it returns a global time context, which has a clock set.

Ahh, you know what? I think you may need to get the `IndependentTimeContext` first by calling `getContextForView(this.objectPath)`, and then once you have that, you can get the active clock by calling `.clock()` on the returned time context. This should give you the upstream time context, which in this case would be the global time context.

That way you won't have to update any code later on.

**Comment by akhenry** [comment]
@ozyx Correct, that's my understanding of how things should work.

**Comment by scottbell** [comment]
@akhenry @ozyx Thanks for the input! Hopefully I've got it right now in the two PRs I've issued. I'm adding tests, but I think they're ready for review.

**Comment by ozyx** [comment]
Verified Fixed -- Testathon 10/24/22
