### ISSUE TITLE
Implement Yamcs Fault Management adapters

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#140]
**Is your feature request related to a problem? Please describe.**
Open MCT now supports a Fault Management interface. This issue is for tracking the work to integrate Open MCT fault management with Yamcs' faults API

#### Verifying Fault Management functionality
1. Verify that new faults are received in real-time per the testing instructions included in https://github.com/nasa/openmct/issues/5052#issuecomment-1149192992
2. Verify that after a WebSocket is closed Faults can still be received in real-time without a refresh once the WebSocket is re-established. This could potentially be tested by restarting Yamcs.

#### Real-time telemetry regression testing
The associated PR that implements this includes extensive changes to WebSocket management in Open MCT. As such, we need to ensure that websockets are still working as expected and that they remain resilient to dropouts
1. Ensure that real-time data is flowing as expected
2. Verify that VIPEROMCT-111 is still resolved.
3. Verify that after a WebSocket is closed telemetry subscriptions are automatically re-established and that real-time telemetry automatically starts flowing again without a refresh. This could potentially be tested by restarting Yamcs.

**Comment by charlesh88** [comment]
Verified fixed via verification of https://github.com/akhenry/openmct-yamcs/issues/144 Testathon 07-06-22.
