### ISSUE TITLE
Realtime telemetry completely broken in 2.0.5

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#144]
#### Summary
No subscriptions are being made for any parameters. This is ~~almost~~ certainly due to [recent refactoring of WebSockets](https://github.com/akhenry/openmct-yamcs/pull/127/files#diff-4da409899847f2633a97c8906bc2948b6a2534c8ce6d3a635224ddb063c36ac4R1)

#### Expected vs Current Behavior
Clicking on a parameter should show data arriving in real-time.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Click on any parameter with real-time data flowing.
2. Observe that data is not displayed or updated in real-time.

**Comment by akhenry** [comment]
## Testing Instructions
This refactors the websocket handling and restores it to something closer to its previous behavior.

1. Navigate to a parameter known to have real-time data flowing and verify that the values are updating
2. Navigate to a display of multiple parameters with real-time data flowing and verify that all are updating as expected
3. Simulate a WebSocket dropout and verify that the application recovers and data begins to flow again once the connection is re-established.

**Comment by ozyx** [comment]
Verified -- Testathon 7/6/22

Case 3, after toggling wifi, websocket reconnects and telemetry begins to flow again
