### ISSUE TITLE
Adjust parameter archive queries so that start and stop parameters are always inclusive.

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#147]
This is also tracked as VIPERGDS-917 and [has previously been found in Open MCT testing](https://github.com/nasa/openmct/issues/5111#issuecomment-1113788715).

#### Summary
The `start` and `stop` query parameters in Yamcs archive requests are variously inclusive and exclusive depending on sort order. Specifically:
* Ascending: `[start, stop)` - ie. inclusive `start`, exclusive `stop`
* Descending: `[stop, start)` - ie. inclusive `stop`, exclusive `start`

Open MCT's model is for all time conductor queries to be inclusive. In order to adapt to Yamcs' model we could just adjust the `start` or `stop` parameters of the query (depending on the sort order) by 1ms to render them inclusive.

#### Expected vs Current Behavior
Historical queries should always treat the start and end bounds of the time conductor as inclusive.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Environment
* Open MCT Version: 2.0.5

**Comment by jvigliotta** [comment]
## Testing
- view a telemetry table in fixed mode with one object and with a short timespan (enough for 5 or so rows to show up)
- change the 'end' time to the first row's timestamp
- make sure the first row doesn't disappear
- view a telemetry table in fixed time mode with one object
- change the start time to the timestamp of the row's timestamp
- make sure the row info doesn't disappear

**Comment by ozyx** [comment]
Verified Testathon 7/8/22

Row does not disappear, datum w/ end timestamp in LAD table has data
