### ISSUE TITLE
[Documentation] Document how to run a docker-compose file of openmct-yamcs with yamcs quickstart

### ISSUE THREAD

**Issue by unlikelyzero** [akhenry/openmct-yamcs#159]
This repo does not have any build automation or testing. We need an automated test for this scenario: https://github.com/akhenry/openmct-yamcs/issues/144 

We should march towards that goal with the following:

1.   Provide the community with a rapid -- yet tested -- way of integrating yamcs and openmct
2. Automatically detect changes on yamcs and openmct and run through a series of steps
3.  Stand up a docker-compose file which contains yamcs quickstart, openmct-yamcs, openmct, and some integration tests
4.  Define a "stable" and "bleeding edge" version of yamcs to test against to provide a reference point of stability in a test matrix

To get to this point, we need to do the following:
- [x] Document the steps necessary to run quickstart, openmct-yamcs, and openmct with as much "containerization" as possible
- [x] Convert those steps into a shell script
- [x] Update existing CI configuration to execute that shell script on PR and Nightly
- [x] Create `Copy openmct e2e suite` script to copy the e2e tests from `openmct/e2e` to execute against this quickstart environment
- [x] Create new yamcs verification suite in `openmct/e2e` folder to execute against quickstart and VIPER

**Comment by unlikelyzero** [comment]
# Testing Instructions
- Run through the setup
- Execute an e2e test

**Comment by scottbell** [comment]
@unlikelyzero Ran into this trying to run [the README](https://github.com/akhenry/openmct-yamcs/blob/master/tests/e2e/README.md):
```
$ make all
/Applications/Xcode.app/Contents/Developer/usr/bin/make yamcs-simulator
docker-compose down -v --remove-orphans
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory
```
From [StackOverflow](https://github.com/docker/compose/issues/7896), it looks like it's because I don't have Docker running.

**Comment by scottbell** [comment]
> @unlikelyzero Ran into this trying to run [the README](https://github.com/akhenry/openmct-yamcs/blob/master/tests/e2e/README.md):
> 
> ```
> $ make all
> /Applications/Xcode.app/Contents/Developer/usr/bin/make yamcs-simulator
> docker-compose down -v --remove-orphans
> Traceback (most recent call last):
>   File "urllib3/connectionpool.py", line 670, in urlopen
>   File "urllib3/connectionpool.py", line 392, in _make_request
>   File "http/client.py", line 1255, in request
>   File "http/client.py", line 1301, in _send_request
>   File "http/client.py", line 1250, in endheaders
>   File "http/client.py", line 1010, in _send_output
>   File "http/client.py", line 950, in send
>   File "docker/transport/unixconn.py", line 43, in connect
> FileNotFoundError: [Errno 2] No such file or directory
> ```
> 
> From [StackOverflow](https://github.com/docker/compose/issues/7896), it looks like it's because I don't have Docker running.

Yes, this was the issue. Starting Docker Desktop resolved the (rather cryptic) error.

**Comment by scottbell** [comment]
Following [the README](https://github.com/akhenry/openmct-yamcs/blob/master/tests/e2e/README.md) appeared to work after running Docker Desktop. Some of the tests failed, but the setup seemed to work fine.
