### ISSUE TITLE
Tolerate invalid enumeration parameters being returned from Yamcs

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#161]
**Is your feature request related to a problem? Please describe.**
Yamcs will sometimes return enumeration type parameters with no `enumValues` attribute provided. This causes an error while parsing the telemetry dictionary in Open MCT because [the expected `enumValues` attribute is undefined](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/object-provider.js#L376)). An enumeration type parameter is expected to also define its possible states. See VIPERGDS-1018 for more details.

**Describe the solution you'd like**
We should modify the openmct-yamcs object provider so that instead of throwing an error it will return an empty array of possible values. This is a temporary solution, the long term fix is to have Yamcs provide valid enumeration parameter definitions.

**Comment by unlikelyzero** [comment]
### Testing Notes
- Regression testing around enumeration types from a viper dictionary

**Comment by akhenry** [comment]
Regression testing with enumeration types:
1. Added an enumeration telemetry type to a plot and verified that it plotted correctly
2. Added an enumeration telemetry type to a table and verified that it display the enumerated values correctly
