### ISSUE TITLE
Limit all queries to 1000 results for now

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#18]
Queries to YAMCS for > 1000 results are returning errors. Longer term, Open MCT needs a strategy for handling this but for now we should limit queries to 1000 results in order to prevent errors.

The fix for this is to modify the [historical telemetry provider](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/historical-telemetry-provider.js) to set an upper bound on the `limit` parameter. If a view requests > 1000 results the telemetry provider should just cap it at 1000.

**Comment by merose** [comment]
You might also look at how the continuation token is handled in https://github.com/akhenry/openmct-yamcs/pull/16. See `accumulateResults()` in utils.js.

**Comment by jvigliotta** [comment]
## Testing
- view any telemetry that's query will have a limit greater than 1000
- verify there are no errors
