### ISSUE TITLE
[Events] Websocket connection for realtime event telemetry fails to establish

### ISSUE THREAD

**Issue by ozyx** [akhenry/openmct-yamcs#180]
#### Summary

Open MCT fails to establish a websocket connection to YAMCS Events endpoint. 

In the network tab, constant disconnect/reconnect attempts can be seen after navigating to the Events object.

#### Expected vs Current Behavior

The Events subscription should establish without issue, but it's constantly disconnecting / attempting to reconnect.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Start Open MCT yamcs with yamcs quickstart and telemetry script running
2. Navigate to 'Events'
3. Open network tab and see the websocket connection for events fails to establish

#### Environment
* Open MCT Version: 2.1.0-SNAPSHOT
* Deployment Type: openmct-yamcs
* OS: any
* Browser: any

**Comment by akhenry** [comment]
@akhenry to test

**Comment by akhenry** [comment]
Verified Fixed. Navigated to events object, no errors were observed. Verified that events are received in real-time.

**Comment by davetsay** [comment]
verified.

for funsies i disconnected from network using network throttling, sent an event (which didn't come in), reconnected and and the message then was recieved and all further events were received to openmct.
