### ISSUE TITLE
Search isn't working for aggregate parameters

### ISSUE THREAD

**Issue by scottbell** [akhenry/openmct-yamcs#184]
#### Summary
Searching in OpenMCT for telemetry/parameters doesn't work for children of aggregate parameters.

#### Expected vs Current Behavior
Children of aggregate parameters should return that match the search query.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Search for a child of an aggregate parameter in OpenMCT
2. Notice no results

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Additional Information
Initial investigation by @akhenry revealed it's due to some additional query parameters we need to add to the [YAMCS telemetry query](https://docs.yamcs.org/yamcs-http-api/mdb/list-parameters/), specifically `searchMembers` should be `true` and `details` should be `false`.

**Comment by unlikelyzero** [comment]
@scottbell can you check to see if this PR addresses https://github.com/akhenry/openmct-yamcs/issues/69#issuecomment-1257061492

**Comment by unlikelyzero** [comment]
Re-opening to retest after the openmct blocker is fixed

**Comment by akhenry** [comment]
@jvigliotta to test

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon 10/6

New issue found: VIPEROMCT-197
