### ISSUE TITLE
[CI] Add basic e2e suite with github actions

### ISSUE THREAD

**Issue by unlikelyzero** [akhenry/openmct-yamcs#193]
#### Summary
We need to add test coverage capabilities to this repo so that simple changes don't cause major regressions downstream. Extension of https://github.com/akhenry/openmct-yamcs/issues/183

- [ ] Workflow is triggered on every PR
- [ ] Workflow has pass/fail criteria on PRs
- [ ] Workflow continues to work on local execution as well as in CI

FUTURE
- [ ] [Add yamcs and openmct matrix support to workflow](https://github.com/akhenry/openmct-yamcs/issues/192)

**Comment by unlikelyzero** [comment]
### Testing Notes

1. Open a PR. Verify that e2e tests run on the newly created PR and the test results are archived to the run
3. On the Open PR, trigger the tests with the appropriate github label (leaving this vague for the interested reader)

**Comment by ozyx** [comment]
Verified - Testathon 10/27/22

Following testing procedures. e2e tests were triggered and successfully ran on PR open, and on label add
