### ISSUE TITLE
[Build] Add minimum supported node version to package.json

### ISSUE THREAD

**Issue by unlikelyzero** [akhenry/openmct-yamcs#194]
#### Summary
Some of the dependencies sourced in open mct require node>14 and we shouldn't try to manage two disparate matrices.

- [ ] Add minimum supported node version to package.json
- [ ] Add npm run build:example to general CI checks

**Comment by unlikelyzero** [comment]
### Testing Notes
Attempt to build on node 10 and node 18. Should fail.
Attempt to build on node 14. Should pass

**Comment by ozyx** [comment]
Verified. The build does not fail, but we get this warning:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'openmct-yamcs@2.1.3-SNAPSHOT',
npm WARN EBADENGINE   required: { node: '>=14.19.1 <18.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.9.1', npm: '8.19.1' }
npm WARN EBADENGINE }
```

**Comment by ozyx** [comment]
No warning for node 10 because the version of `npm` doesn't support this feature? (assuming??)
