### ISSUE TITLE
Consider resolving YAMCS dictionary on demand, not on load.

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#20]
Right now the entire YAMCS dictionary (ie. the mission database) is resolved on application load. Given that YAMCS queries are now limited to 1000 results, with a continuation token required for each subsequent query, we might consider resolving the YAMCS dictionary on demand rather than eagerly loading the entire thing. The size of the dictionary in the VIPER mission is now 10s over thousands of parameters, which requires downloading several megabytes of data every time the user opens the application.

When might dictionary entries be requested?
* On search
* When a node in the object tree is expanded
* When a display is loaded (it will reference dictionary entries which may or may not have been request already).

There are trades here. Loading the dictionary once and keeping it in memory means that subsequent access to telemetry objects is instantaneous. However it can make the initial load much slower. So, some prototyping and performance profiling is needed.

We should implement an initial prototype of on-demand loading and do some performance profiling on it under some typical usage scenarios, and compare it to the current implementation where we load the entire dictionary up-front.

eg.
* How long does it take to load the application with many branches of the tree open?
* How long does it take to refresh on a complex display?
* How long does it take to navigate to a complex display once already loaded?

Note that we should use `batchGet` - https://docs.yamcs.org/yamcs-http-api/mdb/batch-get-parameters/

**Comment by scottbell** [comment]
@akhenry Working on an initial implementation, but one possible hangup I can see is that calls to `openmct.telemetry.getMetadata` are going to need to be `async`, as we won't have the metadata on hand necessarily from YAMCS.

**Comment by scottbell** [comment]
> @akhenry Working on an initial implementation, but one possible hangup I can see is that calls to `openmct.telemetry.getMetadata` are going to need to be `async`, as we won't have the metadata on hand necessarily from YAMCS.

Talked with @akhenry, and `openmct.telemetry.getMetadata` can only be called once an object has been resolved, so we should be ok with this.

**Comment by scottbell** [comment]
> > @akhenry Working on an initial implementation, but one possible hangup I can see is that calls to `openmct.telemetry.getMetadata` are going to need to be `async`, as we won't have the metadata on hand necessarily from YAMCS.
> 
> Talked with @akhenry, and `openmct.telemetry.getMetadata` can only be called once an object has been resolved, so we should be ok with this.

@akhenry looking into this more this morning, the only bit of that's waiting on the dictionary load to finish (that I can tell right now) is the [OperatorStatusTelemetry](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/user/operator-status-telemetry.js#L72). It's waiting for all the `yamcs.operatorStatus` types to be loaded, so we can provide roles/telemetry objects/etc. for polling. I think the way it's currently architected, we could have an explicit path in YAMCS to load these telemetry objects, and wait on that instead of the whole dictionary, but we'd need to configure that location in the plugin configuration. What are your thoughts?

In the interim, I'm going to break operator status so we can test performance on lazy loading in general.

**Comment by akhenry** [comment]
After some discussion on this we are going to pursue browser-caching as this addresses the most evident performance bottleneck (application loading time) with the least effort.

Longer term we should assess the in-memory size of the full dictionary and then re-assess whether lazy-loading the dictionary (either directly from Yamcs, or indirectly via IndexDB) might be a useful way of reducing memory usage.

**Comment by scottbell** [comment]
Closing issue for now and looking into caching instead.
