### ISSUE TITLE
realtime-provider accumulates duplicate subscriptions on websocket close and reconnect

### ISSUE THREAD

**Issue by AdamElliott-AB** [akhenry/openmct-yamcs#209]
#### Summary
If the websocket gets closed externally, realtime-provider will
  1. reconnect the websocket
  2. resubscribeToAll() of it's old subscriptions as stored in subscriptionsByCall
  3. each subscription reply message causes another entry to be added to subscriptionsByCall
https://github.com/akhenry/openmct-yamcs/blob/41523015968e0c245bb757de6353a257d658ee71/src/providers/realtime-provider.js#L187
If the websocket gets closed externally again, then realtime-provider repeats 1-3 except that each original subscription is made twice.
Each subsequent websocket disconnect results in a doubling of the number of subscriptions made compared to the previous websocket connection. If this cycle is repeated enough times, it can have a negative performance impact on both the client and server even if the original number of subscriptions was small.

#### Expected vs Current Behavior
Expected to not duplicate subscriptions after websocket reconnects

#### Impact Check List
More likely to have a negative performance impact when the system is already overloaded and dropping websocket connections more frequently.
Workaround is to have users refresh their OpenMCT pages regularly.

#### Steps to Reproduce
The simplest is to open a OpenMCT page for a single parameter
Externally close the websocket multiple times and observe the websocket subscription messages using the browser's inspect mode

#### Environment
* Open MCT Version: 1.8.1
* openmct-yamcs version: 129aa270c6bef49830fbe0c258a34373fce4b475 from Oct 4, 2021
* openmct + yamcs reverse-proxied by nginx
* ubuntu and docker
* Browser: Chrome

#### Additional Information
One solution may be to update the resubscribeToAll() method to clear the subscriptionsByCall map before resubscribing
    	// clone subscriptionsByCall
    	let subscriptionsByCallClone = new Map(this.subscriptionsByCall);
    	// clear subscriptionsByCall
    	this.subscriptionsByCall.clear();
    	// iterate over subscriptionsByCall clone
    	subscriptionsByCallClone.forEach((subscriptionDetails) => {
            this.sendSubscribeMessage(subscriptionDetails);
        });

**Comment by scottbell** [comment]
I was able to replicate killing/restarting YAMCS. The websocket connections grew each time YAMCS was restarted:

https://user-images.githubusercontent.com/9853862/195288475-7b1645ed-9262-4fcd-9c52-cf31417e5fc7.mov

Looking into fix now (thanks for the info @AdamElliott-AB!)

**Comment by scottbell** [comment]
After further investigation, it looks like Chrome keeps old (and disconnected) websockets around in the DevTools for inspection. Under timing, you can see the connection is "done" though, e.g.:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/9853862/195330227-5c5afb43-ee60-48fe-9b82-f08d326cc1ba.png">

Firefox gives a nicer display stating at least that the "Connection Closed":
<img width="730" alt="image" src="https://user-images.githubusercontent.com/9853862/195329404-f4f1bc7d-53ff-4c2f-99b5-5472ad43e0a3.png">

From the YAMCS admin page though, by looking at the HTTP traffic, we don't see any increase in websocket connections:
<img width="1048" alt="Screen Shot 2022-10-12 at 1 21 45 PM" src="https://user-images.githubusercontent.com/9853862/195330343-81bc3210-9214-4f6d-ad61-57fa9d9d30f0.png">

**Comment by scottbell** [comment]
@akhenry for next steps, I've got [a draft PR](https://github.com/akhenry/openmct-yamcs/pull/216) to clean up some of the disconnecting/reconnecting logic, but it's more housekeeping than fixing this issue.

**Comment by AdamElliott-AB** [comment]
@scottbell the issue is not an increase in the number of websocket connections, but an increase in the number of parameter subscription request messages within the new websocket connections.

Also, you can manually kill websocket connections from Yamcs' Admin Area -> Client connections page. That way you won't need to kill/restart Yamcs

**Comment by scottbell** [comment]
I added some debug statements to the [top of connect()](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/realtime-provider.js#L151) to print the size of the subscriptions:

```
console.debug(`🍇 size of subscriptionsByCall ${this.subscriptionsByCall.size}`);
console.debug(`🍇 size of subscriptionsById ${Object.keys(this.subscriptionsById).length}`);
```

and then ran, disconnecting and reconnecting a few times:
```
Established websocket connection to ws://localhost:9000/yamcs-proxy-ws/
realtime-provider.js?3884:245 Websocket closed. Attempting to reconnect...
realtime-provider.js?3884:156 🍇 size of subscriptionsByCall 0
realtime-provider.js?3884:157 🍇 size of subscriptionsById 1
realtime-provider.js?3884:162 WebSocket connection to 'ws://localhost:9000/yamcs-proxy-ws/' failed: 
realtime-provider.js?3884:245 Websocket closed. Attempting to reconnect...
realtime-provider.js?3884:156 🍇 size of subscriptionsByCall 0
realtime-provider.js?3884:157 🍇 size of subscriptionsById 1
realtime-provider.js?3884:162 WebSocket connection to 'ws://localhost:9000/yamcs-proxy-ws/' failed: 
realtime-provider.js?3884:236 Websocket error, attempting reconnect...
realtime-provider.js?3884:245 Websocket closed. Attempting to reconnect...
realtime-provider.js?3884:156 🍇 size of subscriptionsByCall 0
realtime-provider.js?3884:157 🍇 size of subscriptionsById 1
realtime-provider.js?3884:168 Established websocket connection to ws://localhost:9000/yamcs-proxy-ws/
realtime-provider.js?3884:245 Websocket closed. Attempting to reconnect...
realtime-provider.js?3884:156 🍇 size of subscriptionsByCall 0
realtime-provider.js?3884:157 🍇 size of subscriptionsById 1
realtime-provider.js?3884:162 WebSocket connection to 'ws://localhost:9000/yamcs-proxy-ws/' failed: 
realtime-provider.js?3884:236 Websocket error, attempting reconnect...
realtime-provider.js?3884:245 Websocket closed. Attempting to reconnect...
realtime-provider.js?3884:156 🍇 size of subscriptionsByCall 0
realtime-provider.js?3884:157 🍇 size of subscriptionsById 1
realtime-provider.js?3884:162 WebSocket connection to 'ws://localhost:9000/yamcs-proxy-ws/' failed: 
realtime-provider.js?3884:245 Websocket closed. Attempting to reconnect...
realtime-provider.js?3884:156 🍇 size of subscriptionsByCall 0
realtime-provider.js?3884:157 🍇 size of subscriptionsById 1
realtime-provider.js?3884:168 Established websocket connection to ws://localhost:9000/yamcs-proxy-ws/
```

The two data structures seem to be keeping the same size.

**Comment by scottbell** [comment]
Let me check that the number of messages per websocket connection is not increasing.

**Comment by scottbell** [comment]
I ran the YAMCS server on a separate machine, then periodically killed the websocket connection to OpenMCT. It looks like websocket is rebuilt, and subscriptions inside the websockets aren't being duplicated (i.e., we're only getting one copy of the message in the websocket):
<img width="723" alt="Screen Shot 2022-10-13 at 12 47 44 PM" src="https://user-images.githubusercontent.com/9853862/195578306-4399f7d6-8699-441f-bdc8-8b08fb8a0b20.png">

**Comment by scottbell** [comment]
@AdamElliott-AB If you can, I'd try the newer version of this plugin and see if you're still seeing the issue.

**Comment by AdamElliott-AB** [comment]
Thanks for testing @scottbell The version of openmct-yamcs I am working with is a year old now. I am glad this issue is resolve in the latest version. Looking through the history, I believe this issue was corrected in commit "Fixed real-time and historical for regular telemetry" https://github.com/akhenry/openmct-yamcs/commit/d2dbc97d20c49377d9031e04197810cccf029c8c#
by the following change
+    reconnect() {
+        this.subscriptionsByCall.clear();

**Comment by scottbell** [comment]
@AdamElliott-AB Great! And thanks for hunting down the commit. I'll close the issue for now, but please reopen if you run into it again.

**Comment by unlikelyzero** [comment]
@AdamElliott-AB would you mind updating to @latest ?

**Comment by AdamElliott-AB** [comment]
@unlikelyzero Unfortunately not at this time. We are in the testing phase of our current project and only pulling in critical changes such as bugfixes or security patches.
