### ISSUE TITLE
Investigate moving WebSocket handling to workers

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#213]
**Is your feature request related to a problem? Please describe.**
WebSocket callbacks are handled on the main thread, and [performance gains can be realized by moving this handling to a worker](https://bugs.chromium.org/p/chromium/issues/detail?id=456476#c30). 

Blocking WebSocket callbacks can result in queues of messages to be processed which will never actually be seen by a user, so we are wasting CPU cycles handling this data.

**Describe the solution you'd like**
One potential architecture to explore is to have the worker receive streamed messages from Yamcs and simply update a "latest value" table. In order to receive an update, the main thread would have to send a "ready" signal to the worker, perhaps triggered by RAF. The would would then send a message to update the main thread with only the latest values that have changed, along with the number of values "dropped". We could also potentially do timestamp parsing in the worker, as this is a common bottleneck on the main thread.

**Describe alternatives you've considered**
We are already using `requestAnimationFrame` in our views to throttle UI updates, but we are _still_ sometimes seeing cases where Open MCT displays "fall behind" other displays over time, and will be seen to periodically "race" to catch up. This may be because, despite throttling UI updates, the main thread is still being forced to handle _all_ messages received on the WebSocket and they are backing up in a message queue waiting to be processed.

**Comment by scottbell** [comment]
> We could also potentially do timestamp parsing in the worker, as this is a common bottleneck on the main thread.
It's amazing how much CPU time this takes.

**Comment by scottbell** [comment]
@akhenry one other thing that may help is to look at the native [Broadcast Channels](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) to [help with pub/sub](https://pike96.com/posts/websocket-sharedworker-broadcastchannel/).

**Comment by akhenry** [comment]
Testing notes here - https://github.com/akhenry/openmct-yamcs/issues/424#issuecomment-1981656350
