### ISSUE TITLE
Search with YACMS not handling underscores properly

### ISSUE THREAD

**Issue by scottbell** [akhenry/openmct-yamcs#215]
#### Summary
When an operator searches with a query using underscores, the search result doesn't telemetry (with underscores) that matches.

#### Expected vs Current Behavior
Telemetry with underscores should be returned when we search with underscores.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Search for a telemetry value with underscores
2. Observe no telemetry names with underscores are returned

https://user-images.githubusercontent.com/9853862/195062974-e249e69e-3622-4824-a6a1-eb2402813b86.mov

**Comment by scottbell** [comment]
As a workaround, don't include the underscore in the search query.

**Comment by scottbell** [comment]
The issue is there isn't a `Position_x`, there's a `Position.x`. We [replace](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/object-provider.js#L400) the `.` with an underscore. Searching for `Position.x` yields the correct response. This is a little tricky to solve as the parameter name itself may contain underscores, but we're also using it as an aggregate member delimiter.

**Comment by akhenry** [comment]
So it looks like the _ [is being added by us as a way of contextualizing aggregate members](https://github.com/akhenry/openmct-yamcs/blob/0bdf0a816349b66dde862ecaef4bf24e76efdb43/src/providers/object-provider.js#L445). Luckily it's only in the name itself, it's not in the identifier, so we can change this trivially. I think the thing to do is just change that line of code to use `.` as the delimiter for aggregate members, and call it a day.

@jvigliotta @scottbell Thoughts?

**Comment by scottbell** [comment]
@akhenry It’s not clear to me why an underscore was used, though I speculate it’s due to dot notation being used to address objects in OpenMCT? I think it’s worth taking a shot at using a period and seeing what breaks.

**Comment by akhenry** [comment]
We use `:` as a delimiter for serializing object identifiers, but I don't _think_ we rely on `.` anywhere? (except when referencing object property paths but that's not applicable here).

In any case, this is just the object name, which is just presented to the user and not referenced anywhere else, so we should be able to safely use `.`.

**Comment by scottbell** [comment]
Ok! Yeah, this is a very eas my change then.

**Comment by jvigliotta** [comment]
@scottbell @akhenry I took a look, not seeing why we couldn't just replace with a `.`

**Comment by unlikelyzero** [comment]
Searching for ADC_ and POSition returned appropriate yamcs results
