### ISSUE TITLE
Code cleanup - this.dictionary and this.objects

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#218]
#### Summary
For some reason we have both [`dictionary`](https://github.com/akhenry/openmct-yamcs/blob/913257bac8c892e467126c481f32dd377555d0c1/src/providers/object-provider.js#L45) and [`objects`](https://github.com/akhenry/openmct-yamcs/blob/913257bac8c892e467126c481f32dd377555d0c1/src/providers/object-provider.js#L48) attributes on our Yamcs object provider. They are identical -

```JavaScript
this.dictionary === this.objects
true
```

Prefer `this.dictionary`, so please get rid of `this.objects`.

**Comment by scottbell** [comment]
To test:

- Start OpenMCT with YAMCS as normal
- Ensure parameter objects & spacesystems load
- Open network tab in DevTool and ensure collapsing and expanding tree object doesn't cause a network request.

**Comment by unlikelyzero** [comment]
Verified
