### ISSUE TITLE
YAMCS Proxy fails with node version >=18

### ISSUE THREAD

**Issue by ozyx** [akhenry/openmct-yamcs#223]
#### Summary

The YAMCS proxy (using yamcs quickstart) fails to establish if running `openmct-yamcs` with node >=18. Downgrading to node 16 resolves the issue.

#### Expected vs Current Behavior

The YAMCS proxy should establish successfully, but it doesn't.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Run YAMCS quickstart (I used YAMCS v5.6.2)
2. Using node v18 in openmct-yamcs: `npm i; npm run build:example; npm start`
3. Notice that YAMCS proxy fails to establish and telemetry fails to load

#### Environment
OpenMCT:
```
Version: 2.1.1
Build Date: Wed Oct 12 2022 11:42:16 GMT-0700 (Pacific Daylight Time)
Revision: db495ea12ecc4f77bd651d655ccb062b5eef5e14
Branch: release/2.1.1
```

OpenMCT-YAMCS:
latest @ commit 23a3a83c973a1ff830cc9a665a182726d8ac60e6

Node v18.9.1

#### Additional Information

```
<i> [webpack-dev-server] [HPM] Upgrading to WebSocket
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000 to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<i> [webpack-dev-server] [HPM] Upgrading to WebSocket
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000 to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000api/user/ to http://localhost:8090/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<i> [webpack-dev-server] [HPM] Upgrading to WebSocket
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000 to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000api/mdb/myproject/space-systems to http://localhost:8090/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<i> [webpack-dev-server] [HPM] Upgrading to WebSocket
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000 to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<i> [webpack-dev-server] [HPM] Upgrading to WebSocket
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000 to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<i> [webpack-dev-server] [HPM] Upgrading to WebSocket
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000 to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by unlikelyzero** [comment]
I've put in an engine check on node18 until we can figure out what's causing the failure. When someone fixes this, please update the engine check and add node 18 to our CI matrix

**Comment by unlikelyzero** [comment]
This appears to be fixed

**Comment by unlikelyzero** [comment]
### Testing Notes
Verify that it's possible to run quickstart + openmct-yamcs with node18
