### ISSUE TITLE
Better websocket debugging

### ISSUE THREAD

**Issue by unlikelyzero** [akhenry/openmct-yamcs#227]
STUB FOR https://github.com/akhenry/openmct-yamcs/pull/216

**Comment by unlikelyzero** [comment]
Scott, can you add some testing notes on how to trigger the reconnect logic?

**Comment by scottbell** [comment]
To test:

- Browse to a parameter that has updating telemetry (like `A`)
- Bring up the JavaScript console
- Turn off your network
- Ensure the Javascript console displays that the websocket connection had been lost and had been closed.
- Turn network on
- Ensure Javacript console displays that the websocket connection has been reestablished.

**Comment by ozyx** [comment]
Testathon 10/27/22:

I was not able to verify, maybe I was on the wrong parameter? I shut off my network (VPN + WIFI) and was not able to trigger the "connection lost" and "reconnect" messages. I did see this on connect, however:

`🔌 Established websocket connection to wss://banner.ndc.nasa.gov/yamcs/api/websocket`

**Comment by ozyx** [comment]
Testathon 10/27/22:
 
I was not able to verify, maybe I was on the wrong parameter? I shut off my network (VPN + WIFI) and was not able to trigger the "connection lost" and "reconnect" messages. I did see this on connect, however:
 
`🔌 Established websocket connection to <insert super secret url here>`

**Comment by scottbell** [comment]
@ozyx Well, at least we know the code made it over! A couple of caveats:

- Testing locally, I had to kill `webpack-dev-server` to make it disconnect the websocket (see attached video)
- Turning off my wifi wasn't enough
- The network tab in Chrome's DevTools does allow you to [throttle websocket requests](https://developer.chrome.com/en/blog/new-in-devtools-99/), but confusingly doesn't appear to work for "No network".


https://user-images.githubusercontent.com/9853862/198556107-49e19d3b-7e3e-4892-9b90-6377cc40c7f6.mov
