### ISSUE TITLE
[Fault Management] Duplicate requests on mount

### ISSUE THREAD

**Issue by ozyx** [akhenry/openmct-yamcs#245]
#### Summary

Duplicate requests to YAMCS are sent out whenever the Fault Management object is focused.

#### Expected vs Current Behavior

Only one request should happen

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Launch openmct-yamcs with quickstart, or go to our testing environment
2. Open browser debugger and network tab
3. Click the Fault Management domain object
4. Observe duplicate requests to YAMCS 'alarms' endpoint

#### Environment
* Open MCT Version:  2.1.4-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Additional Information

[One request is being triggered from Vue on mount on the openmct side.](https://github.com/nasa/openmct/blob/05e3303828b6ce0fc705329b1b6e16cf36b2fbf7/src/plugins/faultManagement/FaultManagementView.vue#L46)

[The other request is triggered on the first websocket message received (on openmct-yamcs side).](https://github.com/akhenry/openmct-yamcs/blob/594364c538175d6ff75c0d2dcdf41b01fb31d586/src/providers/realtime-provider.js#L224)

**Comment by ozyx** [comment]
# Testing Instructions

- Open up "Network" tab of dev tools and make sure it's been cleared
- Navigate to Fault Management
- Verify only one request to YAMCS occurs on mount

**Comment by michaelrogers** [comment]
Fix verified during testathon 03/30/2023.
