### ISSUE TITLE
[Images] "samples" endpoint should never be used for imagery telemetry

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#27]
Requests for historical images sometimes use the /samples/ endpoint, and at other times does not. The `/samples` endpoint does not work for images (presumably because url strings cannot be easily aggregated).

**Comment by akhenry** [comment]
This relates to https://github.com/akhenry/openmct-yamcs/issues/3 and should be considered at the same time that this issue is fixed.

**Comment by jvigliotta** [comment]
### Testing
- request historical imagery on a yamcs implementation of openmct, open network tab and verify "samples" endpoint isn't being called

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 3/3/2021

Not seeing any image requests using samples endpoint.

**Comment by davetsay** [comment]
verified
