### ISSUE TITLE
Potential for telemetry to be "missed" by subscribers

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#271]
#### Summary
[An optimization in the openmct-yamcs plugin](https://github.com/akhenry/openmct-yamcs/blob/80b9d96979a27fec4f60e1cc3f1c84b4162eab65/src/providers/historical-telemetry-provider.js#L59) short-circuits requests for latest data in real-time mode with the assumption that [a subsequent subscription callback will provide the requested data](https://github.com/akhenry/openmct-yamcs/blob/80b9d96979a27fec4f60e1cc3f1c84b4162eab65/src/providers/messages.js#L62).

This creates an edge-case that we should address, ~~and some investigation to see whether it's actually replicable in our current codebase~~. It is.

The Telemetry API [multiplexes multiple subscriptions down to just a single provider subscription](https://github.com/nasa/openmct/blob/87901834bb8dc78b0a800b47cb1d9b484936d062/src/api/telemetry/TelemetryAPI.js#L409). The working assumption in our latest data optimization is that Yamcs will provide us with the latest telemetry value immediately upon subscription. However this assumption fails in some cases due to the previously mentioned multiplexing.

If client code subscribes to a parameter that does not update very often, and for whatever reason misses the initial subscription callback that includes the latest value, it will have no data until the telemetry point next updates. There are many, many reasons why client code might miss the initial subscription callback because of the asynchronous nature of how Open MCT operates.

#### Expected vs Current Behavior
Calling code should always receive the latest data when requested.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
~~Unknown, investigation required.~~ I believe that this issue has been recreated in https://github.com/nasa/openmct/pull/6108#issuecomment-1399041117

**Comment by ozyx** [comment]
FWIW this change was blocking historical requests for imagery metadata causing this bug: https://github.com/nasa/openmct/issues/6074

Not exactly the same scenario as mentioned, but an edge case where we were losing telemetry nonetheless.

**Comment by akhenry** [comment]
I believe that this issue has been recreated [here](https://github.com/nasa/openmct/pull/6108#issuecomment-1399041117).

**Comment by scottbell** [comment]
@akhenry the naive thing to do here is just [roll back the optimization](https://github.com/akhenry/openmct-yamcs/blob/80b9d96979a27fec4f60e1cc3f1c84b4162eab65/src/providers/historical-telemetry-provider.js#L59). I'm seeing if we can do something more sophisticated to keep the optimization, but undoing it is probably the safest course.

**Comment by akhenry** [comment]
Rolling back the optimization is a last resort, we have layouts with hundreds of telemetry points, which means hundreds of historical requests.

There is a third option, which is sub-optimal, but much better than using the parameter archive. We have a [Latest Data Provider](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/latest-telemetry-provider.js#L41) which uses [a different Yamcs endpoint](https://docs.yamcs.org/yamcs-http-api/processing/get-parameter-value/) that [supports batching](https://docs.yamcs.org/yamcs-http-api/processing/batch-get-parameter-values/). We haven't implemented batching in the provider, but we could do a really dumb batching algorithm based on a simple debounce that should 90% work for now.

**Comment by scottbell** [comment]
https://user-images.githubusercontent.com/9853862/217819049-db1a6048-5678-40e8-9e3d-d10cc884a42c.mov

@akhenry I've got a PR that refers requests for historical telemetry (with `latest` and in real time mode) to use the Latest Data Provider in YAMCS instead. This reduces a display layout with 55 items with telemetry to 1 batched call.
