### ISSUE TITLE
`acquisitionStatus` staleness errors in the console when loading up empty telemetry plot

### ISSUE THREAD

**Issue by ozyx** [akhenry/openmct-yamcs#272]
#### Summary

Loading up certain empty plots causes staleness errors to be thrown relating to `acquisitionStatus`

#### Expected vs Current Behavior

No staleness errors

#### Steps to Reproduce

1. Navigate to a bunch of different telemetry on testathon, try to find one that's blank
2. Notice errors in the console regarding staleness

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  testathon
* OS: MacOS
* Browser: chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

![image](https://user-images.githubusercontent.com/9259993/214388837-1b561fcd-9003-4ba4-8928-e275fbf7b30c.png)

**Comment by jvigliotta** [comment]
## Testing
- follow the repro steps

**Comment by ozyx** [comment]
Verified fixed -- Testathon 02-02-2023

**Comment by unlikelyzero** [comment]
@scottbell  to retest on local deployment

**Comment by scottbell** [comment]
Confirmed.
Before fix:
<img width="1043" alt="before" src="https://user-images.githubusercontent.com/9853862/216610070-8d8b12b6-70b6-49c8-aa46-1d4112097bfd.png">

After fix:
<img width="1043" alt="after" src="https://user-images.githubusercontent.com/9853862/216610089-db2bd701-8169-4852-809d-837d54ce43bb.png">
