### ISSUE TITLE
Create an "Export as CSV" action for exporting telemetry points and telemetry tables to CSV

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#280]
**Is your feature request related to a problem? Please describe.**
Users have requested the ability to export large amounts of telemetry data from any telemetry point, grouped by timestamp. 

eg.

```CSV
Timestamp, Parameter 1, Parameter 2, Parameter 3, Parameter 4, Parameter 5
1970-01-01T12:00:00:000, P1V1, P2V1, P3V1, P4V1, P5V1
1970-01-01T12:00:00:001, P1V2, P2V2, P3V2, P4V2, P5V2
```

You can export data as CSV from Open MCT currently, but it is only supported from tables. Telemetry tables organize values differently. Values are not grouped by timestamp, they are all displayed on separate rows. 

eg.
```
Name,Timestamp,Value
Parameter 1, 1970-01-01T12:00:00:000, P1V1
Parameter 2, 1970-01-01T12:00:00:000, P2V1
Parameter 3, 1970-01-01T12:00:00:000, P3V1
Parameter 4, 1970-01-01T12:00:00:000, P4V1
Parameter 5, 1970-01-01T12:00:00:000, P5V1
Parameter 1, 1970-01-01T12:00:00:001, P1V2
Parameter 2, 1970-01-01T12:00:00:001, P2V2
Parameter 3, 1970-01-01T12:00:00:001, P3V2
Parameter 4, 1970-01-01T12:00:00:001, P4V2
Parameter 5, 1970-01-01T12:00:00:001, P5V2
```

**Describe the solution you'd like**
Yamcs already supports what the users have requested through the ["export parameter values"](https://docs.yamcs.org/yamcs-http-api/stream-archive/export-parameter-values/) endpoint. Here's how I propose we use it:

1. Define a new action in the Open MCT - Yamcs repository named "Export as CSV"
2. Define an `appliesTo` function that makes the action applicable to any telemetry object _and any object that has immediate children that are telemetry objects_. This will allow users to group the parameters they want to export in a table, or even just in a folder. `appliesTo` is a synchronous function, so this approach may not entirely work. We may have to allow the action for any object with composition, and show an error message at invoke time if the object has no children that are telemetry objects.
3. In the `invoke` function, call the Export Parameter Values endpoint, passing in the ids of the telemetry objects to export. This will be either the object that the action was invoked on (if it's a telemetry object) or any children that are telemetry objects.

**Describe alternatives you've considered**
We could also support this by enhancing the existing table export. The problem with this approach is that the Export Parameter Values endpoint does not support the type of filtering that our tables provide. Moreover, exporting from a table is slow because the table uses the parameter archive, which is aggressively paged, so exports are slow.

**Comment by shefalijoshi** [comment]
Testing instructions:

0. Find a yamcs telemetry object in the navigation tree 
1. Right click on the object
2. Choose Export to CSV from the menu
3. Assuming there is data available for the telemetry object, a CSV file should be created for the given time range.
4. Repeat steps 1-3 for a folder within the dictionary.
5. Repeat steps 1-3 for an 'aggregate' type within the dictionary 
6. Create a new folder / object with composition and drag telemetry from the VIPER dictionary into it's composition.
7. Repeat steps 1-3 for the object created in step 6.

**Comment by ozyx** [comment]
Verified -- Testathon 3/17/2023 🍀
