### ISSUE TITLE
Color-code Event messages based on Yamcs severity

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#287]
**Is your feature request related to a problem? Please describe.**
The Yamcs event view color-codes event messages based on their severity. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/4215777/224141682-e9e1eea8-bb1d-483d-b60c-970af222f982.png)

Users have requested that this Yamcs color coding is reflected in the Open MCT event stream as well.

**Describe the solution you'd like**

The simplest way to achieve this in Open MCT is by defining [a limit provider](https://github.com/nasa/openmct/blob/master/API.md#limit-evaluators-draft) that provides the appropriate styling rules. [This is already implemented](https://github.com/akhenry/openmct-yamcs/blob/master/src/plugin.js#L78) for Yamcs alarms, so we would just need to define a second limit provider specifically for Events.

I think we have some scope to adjust the colors if they cause legibility issues in our themes, so long as there is some consistency between Open MCT and Yamcs.

**Comment by charlesh88** [comment]
@michaelrogers Checking in on this. I think we should do this via CSS classes to be theme-friendly - the colors near may need to vary a little to play well on the dark and light backgrounds of Espresso and Snow.

**Comment by michaelrogers** [comment]
## How to Test
1. Navigate to Events
2. Observe `WATCH`, `WARNING` have yellow styling via `is-event--yellow` class
3. Observe `DISTRESS`, `CRITICAL`, `and `SEVERE` has red styling via `is-event--red` class
4. Observe all other severities are not styled and have the `is-event--no-style` class applied

**Comment by rukmini-bose** [comment]
This is good! Tested 3/17/2023

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3/17/23

![image](https://user-images.githubusercontent.com/9259993/226062245-9352c661-72f3-4219-afb7-69d0378e687e.png)


looks good
