### ISSUE TITLE
Cancel searches when the search criteria change

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#288]
**Is your feature request related to a problem? Please describe.**
Currently the Open MCT-Yamcs search provider does not cancel outstanding searches when the search criteria change, forcing the browser to wait until all outstanding requests have completed, even if they are no longer relevant.

**Describe the solution you'd like**
The Search API [provides an AbortSignal](https://github.com/nasa/openmct/blob/73734d99eac21d1c9ae882e14e80d4de5e7a4303/src/api/objects/ObjectAPI.js#L278) which is triggered when the search criteria change. The Open MCT-Yamcs search provider seems to be expecting [a slightly different method signature](https://github.com/akhenry/openmct-yamcs/blob/697dc4d5e35f126b7bde299233d62ad380fcd907/src/providers/object-provider.js#L95). All that's needed is to pass the abort signal to the relevant fetch requests in the Yamcs search provider.

**Comment by scottbell** [comment]
To test:

1. Load OpenMCT for YAMCS
2. Throttle network Speed in DevTools
3. Open Network tab in DevTools
4. Slowly start typing in the search box, notice canceled Search requests

**Comment by akhenry** [comment]
verified fixed.
