### ISSUE TITLE
Provide telemetry metadata for array parameters

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#292]
**Is your feature request related to a problem? Please describe.**

Open MCT has some limited support for array type parameter values [in the context of spectral plots](https://github.com/nasa/openmct/blob/1d4cf1ff06573487f3762cbfe34ca0162d080ef0/src/plugins/charts/bar/BarGraphView.vue#L231). Arrays can be specified in telemetry metadata [by appending `[]` to the end of any existing format key. eg. `string[]` `number[]`](https://github.com/nasa/openmct/blob/1d4cf1ff06573487f3762cbfe34ca0162d080ef0/example/generator/GeneratorMetadataProvider.js#L35). Open MCT will then parse the array and apply the designated formatter to each member of the array.

The Open MCT-Yamcs adapter is not currently providing this metadata to Open MCT for array parameter types, preventing them from being used in spectral plots. This issue is to track the work done to add appropriate metadata to [the Yamcs Object Provider](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/object-provider.js) such that the Graph component recognizes the spectral data as arrays.

**Comment by shefalijoshi** [comment]
Testing Instructions:
Create a Graph in Open MCT
Find aggregate telemetry with children with Array parameters or a telemetry endpoint with at least 2 array metadata values.
Drag the telemetry into the Graph
Ensure that the plot renders data with both line and bar types.

**Comment by unlikelyzero** [comment]
Will need to test next week

**Comment by unlikelyzero** [comment]
@unlikelyzero to close
