### ISSUE TITLE
Support filtering by severity for Events Tables

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#314]
**Is your feature request related to a problem? Please describe.**
Yamcs [supports filtering requests for Events by minimum severity](https://docs.yamcs.org/yamcs-http-api/events/list-events/). A little-know, and undocumented feature of Open MCT is that it also [supports server-side filtering](https://github.com/nasa/openmct/blob/1d4cf1ff06573487f3762cbfe34ca0162d080ef0/src/api/telemetry/TelemetryMetadataManager.js#L136) when supported by the adapter by passing filter criteria along with requests to the server. 

**Describe the solution you'd like**
Modify the Open MCT - Yamcs adapter to pass along a severity filter in requests for Events. It doesn't look as though Event subscriptions support filtering however, so we will likely have to just do this in manually [in the Events subscription handler](), which should be pretty straightforward.

**Describe alternatives you've considered**

**Additional context**
You will need some help with this since Open MCT's support for server-side filtering is currently undocumented. The Open MCT for MCWS codebase includes examples, so you will need to work with someone who has access to that codebase for now.

As part of this ticket we should add some basic documentation for this feature of Open MCT for future developers.

**Comment by scottbell** [comment]
@davetsay Showed me that MCWS is open source now!
https://github.com/NASA-AMMOS/openmct-mcws

**Comment by scottbell** [comment]
> NO RADIO BUTTONS! Selects should be used.

But the YAMCS severity filter can only take one option...

**Comment by charlesh88** [comment]
@scottbell Suggest your new option should be called "singleSelectionThreshold" to make it clear it's not just a "single" selection, but instead defines a threshold level.

**Comment by charlesh88** [comment]
Testathon 2023-07-21: unable to verify due to Filters plugin not included in the deployment.

**Comment by ozyx** [comment]
Verified testathon 9/12/23
