### ISSUE TITLE
Consolidate multiple command history state changes into a single command history row.

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#315]
**Is your feature request related to a problem? Please describe.**
Open MCT shows Yamcs command history, but currently the output is very noisy. This is due to the fact that Yamcs issues multiple events for a single message, providing updates on the message's current state.

In this example, two commands are sent. The Yamcs command history table has two entries, but the equivalent table in Open MCT has 16 rows (8 per command).

<img width="828" alt="Command History in Yamcs" src="https://user-images.githubusercontent.com/4215777/234370236-4e800dc6-9459-4f1f-a630-730d249b8edd.png">

<img width="1659" alt="Command History in Open MCT" src="https://user-images.githubusercontent.com/4215777/234370323-d6604a43-828e-43f6-aa7f-a9816fff9315.png">

The issue does not occur with historical commands because we receive a single entry for each command showing its current state.

**Describe the solution you'd like**
When receiving command updates via a subscription we should consolidate the multiple messages into a single row. Some investigation should be performed into the approach that Yamcs uses for consolidating these messages, and we should use that. Are they simply debouncing the updates as they arrive in the client? From a superficial analysis [they appear to be maintaining a buffer](https://github.com/yamcs/yamcs/blob/0c93fcac7d6fcfdda38e7f1850c73b712345d10e/yamcs-web/src/main/webapp/src/app/commanding/command-history/CommandHistoryDataSource.ts#L97).

Or are they strictly maintaining a single row per command? ie. a state update that arrives 5 minutes later will update the existing row in the table, rather than creating a new one.

Strictly maintaining a single row per command is a little more involved because subsequent state updates require us to locate the row for the command, and update it in-place. The Telemetry Table is not designed to do this, and there are performance implications. That said, commands should not be issued so regularly that real-time performance is a significant concern.

**Comment by shefalijoshi** [comment]
**Testing instructions:**
1. Navigate to Commands under the yamcs dictionary
2. Using the yamcs UI, Go to commanding and send a few commands.
3. Ensure that each command sent shows up as only one row and not multiple rows for each partial update for a command.
4. Navigate to any telemetry table that's NOT Commands.
5. 3. Ensure that table rows are not aggregated like it was for Commands.

**Comment by unlikelyzero** [comment]
We need explicit test instructions and compare between 2.2.5 (deployed to /stable)

**Comment by ozyx** [comment]
Verified in Testathon 7/21/23. Great work!
