### ISSUE TITLE
[Folder Type] Update object provider to use new non-editable folder type

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#33]
When the new non-editable folder type plugin is created and added to openmct update the object provider to use this new type of folder. This will prevent "persistence" errors from showing up when trying to edit non-editable folder properties/names.

## Testing
- verify you cannot edit the name (browse bar) or properties (contextmenu) of viper folders

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 3/3/2021

**Comment by davetsay** [comment]
verified
