### ISSUE TITLE
Support for image thumbnails for image objects

### ISSUE THREAD

**Issue by shefalijoshi** [akhenry/openmct-yamcs#341]
Open MCT can display a large number of historical images in its "imagery" and "timeline" views. 

Currently Open MCT pulls down full size images and scales them down to thumbnail scale for preview in-browser. This doesn't scale well for large numbers of historical images, and is not an efficient use of network bandwidth, as most of the images retrieved will not be viewed at their native scale by the user.

The Image Aggregator now produces thumbnail sized "preview" images of full-scale images. We need to expose these in imagery metadata.

Add imagery metadata that exposes imagery thumbnail information for imagery objects.

See: https://github.com/nasa/openmct/issues/5931 and VIPERGDS-840

**Comment by unlikelyzero** [comment]
To test:

- Verify that the direct link to images as telemetry on banner behaves
- Verify that the direct link to images as telemetry on banner behaves with thumbnail preview
- Verify that the Display Layout (all cams 16x) on banner behaves with thumbnail previews

**Comment by ozyx** [comment]
Testathon 7/18/23:

Verified! All scenarios listed above behave correctly and the thumbnail url is used in Imagery Thumbnail strip
