### ISSUE TITLE
Include the Filters plugin by default in Open MCT Yamcs deployments

### ISSUE THREAD

**Issue by charlesh88** [akhenry/openmct-yamcs#348]
**Is your feature request related to a problem? Please describe.**
Event filtering #314 requires the Filters plugin to be installed.

**Describe the solution you'd like**
@akhenry says: let's install it by default in this type of deployment.

**Describe alternatives you've considered**

**Additional context**

**Comment by scottbell** [comment]
@charlesh88 @akhenry @unlikelyzero I think the filters plugin for `openmct-yamcs` is already installed by default in this repository:
https://github.com/akhenry/openmct-yamcs/blob/master/example/index.js#L58

is the test environment perhaps using a different install package? We could also install it with the default [Open MCT environment](https://github.com/nasa/openmct/blob/master/index.html) if desired.

**Comment by scottbell** [comment]
@ozyx I tested using our new [Open MCT Quickstart](https://github.com/scottbell/openmct-quickstart) (which uses the openmct-yamcs repository) and I was able to see the filters:
<img width="1464" alt="image" src="https://github.com/akhenry/openmct-yamcs/assets/9853862/6169990a-1b69-4366-aaac-c5e9f66f2553">


We should catch up and see what our testing environment is doing differently.

**Comment by scottbell** [comment]
Talked with @ozyx and we're going to add it to the plugin definition itself.

**Comment by ozyx** [comment]
Not fixed in the context of VIPER. The Filters tab shows up but Command filtering doesn't show up:

![image](https://github.com/akhenry/openmct-yamcs/assets/9259993/0b3caacc-d9a2-4090-8141-f51423bc47c7)

**Comment by akhenry** [comment]
Verified Fixed! Yay!
