### ISSUE TITLE
[Fault Management] View does not show values for many parameter types

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#380]
#### Summary
When alarms are triggered in Yamcs they show up in the Fault Management display in Open MCT.

This display shows current alarms across the system, including the parameter values that triggered the alarms. In many cases it is not showing these parameter values because the YAMCS fault provider has been hard-coded to only support parameters with `doubleValue`s and not other scalar types (such as `floatValue`s)

#### Expected vs Current Behavior

Should display all values correctly.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Navigate to the Fault Management screen
2. Download and run the attached script from banner
3. Wait for an alarm to be triggered on any of the ViperRover/WheelOdometry/xVelocity, yVelocity, or wVelocity parameters.
4. Observe that the "Trip Value" and "Live Value" columns are empty for these parameters.

**Comment by michaelrogers** [comment]
## How to Test
1. Navigate to Fault Management
2. Wait for an alarm to trigger
3. Observe that all Live and Trigger values are populated with values

**Comment by ozyx** [comment]
Verified Fixed 10/3/2023
