### ISSUE TITLE
Add load tester for YAMCS to simulate Open MCT traffic

### ISSUE THREAD

**Issue by scottbell** [akhenry/openmct-yamcs#388]
#### Summary

Using K6, or by writing a simple Node script, simulate 300 WebSocket clients subscribing to 10Hz telemetry. What
is the impact on YAMCS? What happens if you make the clients slow to service the WebSocket messages, simulating a browser under heavy load? Does the CPU utilization scale up linearly, or is there a threshold at which it suddenly jumps up?

**Comment by scottbell** [comment]
@akhenry @unlikelyzero It looks like the YAMCS Quickstart only [fires at 1Hz](https://github.com/yamcs/quickstart/tree/master#telemetry). Do you guys have another lead on 10Hz data?

**Comment by scottbell** [comment]
@unlikelyzero says to run for an hour before shutting down.

**Comment by akhenry** [comment]
> ~@akhenry @unlikelyzero It looks like the YAMCS Quickstart only [fires at 1Hz](https://github.com/yamcs/quickstart/tree/master#telemetry). Do you guys have another lead on 10Hz data?~
> 
> @unlikelyzero had a smart idea of just running the `simulator.py` 10 times, which gives us 10Hz. It works!

I've for sure had luck simulating 10Hz  data by modifying [this line](https://github.com/yamcs/quickstart/blob/a855eba3ac14e44a17a10612b7ea72e30370a1fe/simulator.py#L26) to be `sleep(0.1)`

**Comment by scottbell** [comment]
> > ~@akhenry @unlikelyzero It looks like the YAMCS Quickstart only [fires at 1Hz](https://github.com/yamcs/quickstart/tree/master#telemetry). Do you guys have another lead on 10Hz data?~
> > @unlikelyzero had a smart idea of just running the `simulator.py` 10 times, which gives us 10Hz. It works!
> 
> I've for sure had luck simulating 10Hz data by modifying [this line](https://github.com/yamcs/quickstart/blob/a855eba3ac14e44a17a10612b7ea72e30370a1fe/simulator.py#L26) to be `sleep(0.1)`

Ah, duh. I've done this before too and had forgotten there's a separate `sleep` above. Thanks for the info!

**Comment by scottbell** [comment]
Adding a 2s "[digestion delay](https://github.com/akhenry/openmct-yamcs/blob/388-add-load-tester-for-yamcs-to-simulate-open-mct-traffic/tests/k6/websocket-subscriptions.js#L67)" for the websocket callback absolutely kills YAMCS:
![pegged](https://github.com/akhenry/openmct-yamcs/assets/9853862/08c40373-9f8e-450c-8298-9aeb0a4e1274)
![memory](https://github.com/akhenry/openmct-yamcs/assets/9853862/6fba511a-cc55-44cf-9559-93ec8cab8772)

and the memory doesn't stays pretty high too, though restarting YAMCS resolves it.

**Comment by scottbell** [comment]
If one comments out this:
```yaml
      webSocket:
        writeBufferWaterMark: { low: 32768, high: 160000000 }
```
it causes a great deal of these messages:
```
16:05:21.647 _global [45] WebSocketServerMessageHandler Channel full, cannot write message with priority=NORMAL (slow network?). Closing connection.
```
but the CPU/memory consumption of YAMCS remains constant.

**Comment by akhenry** [comment]
@scottbell Beautiful! These are great findings. The error message is a symptom of a self defense mechanism against slow clients which we are effectively disabling by using arbitrarily large write buffers. Open MCT can handle being dropped, it will just reconnect again. There's also stuff we can do in Open MCT to make it process WebSocket messages quicker so the buffer doesn't back up, such as taking WebSocket handling off the UI thread.

**Comment by akhenry** [comment]
@scottbell  @unlikelyzero Can we use K6 to load real Open MCT clients? 

I think the next step is to reproduce this with real Open MCT clients so that we have a test bed for measuring Open MCT changes.

We will need a sufficiently complex Open MCT display with a bunch of plots, LAD Tables, alphanumerics, and condition sets / widgets. @charlesh88 has some scripting to automate this I believe.

I think it's worth trying to build a real repro of this in Quickstart for a couple reasons:
1. We can build regression tests that run on our commercial CI environment and don't require NASA resources.
2. We can provide reproductions to the Space Applications team if we identify Yamcs bottlenecks
3. We do not interrupt other development work on shared resources.
4. Folks outside of NASA can potentially contribute to our performance optimization efforts.

**Comment by scottbell** [comment]
@unlikelyzero @akhenry 

There's a [K6 browser](https://k6.io/docs/using-k6-browser/overview/) I think we could use to do this. From what I can tell, we'd need to:

- Spin up OpenMCT for YAMCS pointed to the server we want to load test
- Spin up K6 to create X browsing client to point to various displays using YAMCS data
- Measure YAMCS performance

Playwright looks like it also has [something similar](https://www.artillery.io/docs/reference/engines/playwright) we could do with Artillery, but I'm not familiar with it.

**Comment by scottbell** [comment]
@unlikelyzero @akhenry 
Fiddling with rather modest parameters for K6:
```js
const maxClients = 40;
const workersPerClient = 5;
const digestionTimeInMs = 500;
```
on their own create a rather slow build in memory consumption. But if I stop the K6 process after 10 minutes, and restart it, YAMCS never really gives up the fat websocket buffers from the previous run (or at least not quickly enough) and quickly run out of memory.

**Comment by scottbell** [comment]
I've added a [browser test ](https://github.com/akhenry/openmct-yamcs/pull/390/files#diff-da1483ec9f7e9f013b3691bb11c3b0303514658213e2c374f15453fa034be306R1)too. Will let you know what I find testing it out on YAMCS.
