### ISSUE TITLE
Serialized messages that exceed Yamcs' write buffer length cause WebSocket errors

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#397]
#### Summary
Impacts both Open MCT and Yamcs. Initially we need a minimal reproduction in Yamcs-Quickstart using the default high water mark there.

[Yamcs will drop a socket if the buffer fills up and is no longer writable](https://github.com/yamcs/yamcs/blob/ebcdc82a2bb85d4945a97673626b0a42a30f69c8/yamcs-core/src/main/java/org/yamcs/http/WebSocketServerMessageHandler.java#L95
).  This appears to be due to a [potential impedance mismatch between the buffer used to store the serialized message, and the buffer used to write out to the WebSocket](https://github.com/yamcs/yamcs/blob/ebcdc82a2bb85d4945a97673626b0a42a30f69c8/yamcs-core/src/main/java/org/yamcs/http/WebSocketServerMessageHandler.java#L72).

The prevailing theory is that this occurs when a serialized message is larger than the high water mark of the write buffer. 

Issue is being recorded here first so that we can provide a minimal reproduction of the issue using Yamcs Quickstart with the default settings for high and low water marks -
1. Configure some XTCE for an arbitrarily large binary array that is slightly larger than the default buffer high water mark,
2. Write a script (in python, node, whatever works) to push some binary data into that parameter, using `setParameterValue`.
3. Navigate to the parameter in the Yamcs Web UI and observe that the parameter cannot be viewed.

**Comment by scottbell** [comment]
@akhenry I think I'm reproducing the issue and I've got a PR with a script and an example XTCE. Here's a sample parameter that I've fed ~2.6MB worth of image data to with the default `writeBufferWaterMark`:
<img width="1297" alt="small-watermark" src="https://github.com/akhenry/openmct-yamcs/assets/9853862/2f378937-faa8-4061-9dff-3a3308037d96">
Note the value is missing, and attempting to go to Historical Data either causes Chrome to "Ah, Snap" or just shows blank values.

Here's with `writeBufferWaterMark` set to `160000000`:
<img width="1297" alt="big-watermark" src="https://github.com/akhenry/openmct-yamcs/assets/9853862/11472fbb-c0b6-4717-9438-c2d80188ec40">
Note the value is visible, and you can go to Historical Data, wait, and see values.
