### ISSUE TITLE
Support new Websocket interface for telemetry

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#40]
The WebSocket interface in YAMCS has changed since we first implemented it, and the old interface has now been deprecated.

We need to implement the new WebSocket interface ASAP in order to work correctly with more recent versions of YAMCS.

See https://docs.yamcs.org/yamcs-http-api/websocket/

**Comment by akhenry** [comment]
The websocket interface is still active for parameters as of v5.4.1, so we can defer this change for parameters until our next release.

Events, however, do require use of the new Websocket interface. To minimize risk this late in the release, [the new Websocket interface has been implemented solely for Events]().

**Comment by akhenry** [comment]
This has been [partially implemented for Events only](https://github.com/akhenry/openmct-yamcs/issues/41), needs to also be implemented for Parameters.

**Comment by jvigliotta** [comment]
## Testing 
- view any realtime telemetry and confirm no issues and working as expected
- view events and confirm working as expected

**Comment by akhenry** [comment]
Not fixed. I can see data flowing, but views are not updating. Perhaps callbacks are not being invoked?

**Comment by akhenry** [comment]
Verified fixed!
