### ISSUE TITLE
Request Cache Strategy function instead of promise

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#420]
Can we please make the "request cache strategy" promise a function named `getRequestOptions` since we are ultimately passing that object through as the request options object anyway, so developers could use it to customize the request in other ways based on their platform.

**Comment by davetsay** [comment]
Testing Instructions: on VIPER ticket `Use GDS XTCE version parameters to invalidate client-side cache`

**Comment by jvigliotta** [comment]
Verified Fixed 03/20/24
Followed all directions on the VIPER ticket.
