### ISSUE TITLE
[e2e] MDBOverride limit logic is broken

### ISSUE THREAD

**Issue by unlikelyzero** [akhenry/openmct-yamcs#428]
At the moment, our mdb override limit logic is not clearing the limit values as intended:

https://github.com/akhenry/openmct-yamcs/blob/master/tests/e2e/yamcs/limits.e2e.spec.js#L115-L117

The fix is to use https://docs.yamcs.org/python-yamcs-client/tmtc/client/#yamcs.tmtc.client.ProcessorClient.clear_alarm_ranges

To clear alarm ranges on the given parameter

**Comment by shefalijoshi** [comment]
@unlikelyzero Is this still a valid issue?

**Comment by ozyx** [comment]
solved, this was actually [catching a bug ](https://github.com/akhenry/openmct-yamcs/issues/447)
