### ISSUE TITLE
Remove "heartbeat" from legacy websocket interface

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#43]
Heartbeat was achieved by sending an empty subscribe message to YAMCS, which prompted YAMCS to send a response that includes the latest value of the subscribed point. In images, this was resulting in duplicate data being received and rendered in the view.

I believe that these heartbeat messages are no longer necessary since websocket management is much more robust than it was previously. In the event that a Websocket connection is dropped due to inactivity, Open MCT will simply establish a new connection.

### Testing Notes
* This code change affects websocket management in Open MCT for YAMCS. Keep an eye on realtime data and look for dropouts that might indicate that websockets are timing out and dropping data.

**Comment by jvigliotta** [comment]
Didn't see any errors or drops after having it up for a while.

Verified Fixed - Testathon: 3/3/2021

**Comment by deeptailor** [comment]
Verified Fixed
