### ISSUE TITLE
Staleness, Fault management changed in realtime don't work

### ISSUE THREAD

**Issue by shefalijoshi** [akhenry/openmct-yamcs#434]
#### Summary
Staleness and fault management changes in realtime are not reflected in Open MCT

#### Expected vs Current Behavior

Staleness and Fault Management status should update in realtime.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Create an overlay plot with a telemetry endpoint like the `timelyParameter`
2. Ensure that staleness is setup for this telemetry endpoint (set timely parameter script needs to be for this)
3. Ensure that fault management is setup for this telemetry endpoint (not sure how to set this up)
4. Check that staleness indicators are displayed when data for the telemetry endpoint is stale.
5. Check that fault management works for this telemetry endpoint.

#### Environment
* Open MCT Version: Open MCT 4.0.0
* Deployment Type: dev
* OS: All
* Browser: all

**Comment by unlikelyzero** [comment]
@shefalijoshi needs testing notes

**Comment by ozyx** [comment]
> @shefalijoshi needs testing notes

repro steps above seem to be well enough

**Comment by davetsay** [comment]
tested and confirmed basic behavior.
so, verified? it would be nice to have more coverage on this one, @akhenry , @unlikelyzero 

* staleness seems to trigger and display properly.
* fault management seems to work although parts of the UI were not what i would expect, like being able to shelve and ack-ed alarm. I tested this in the yamcs ui though and it is consistent.

**Comment by charlesh88** [comment]
Testathon 2024-04-04 verified staleness with the timelyParameters and fault management with HS_AFT_AD590_2_FLT.
