### ISSUE TITLE
Binary value mismatch with Open MCT and YAMCS admin UI

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#436]
#### Summary

When looking at binary values in the YAMCS admin UI, they are displayed in Hexadecimal format, they are displayed as Base64 strings in Open MCT.

Binary values in Open MCT should be the same as they are displayed in YAMCS admin UI.

**Comment by jvigliotta** [comment]
## Testing
- view binary data from YAMCS in an Open MCT LAD Table
  - values you can try: /ViperRover/CfeTableServicesCPU1/lastValCrcHex or /ViperRover/DocIo/rawTelemetry or search for "hex" in Open MCT search
  - verify they are in a hexadecimal format and also verify they are the same as they are in the YAMCS admin UI

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by akhenry** [comment]
Verified Fixed
