### ISSUE TITLE
[yamcs] update all references to the post-build9rc8 version of viper-yamcs

### ISSUE THREAD

**Issue by unlikelyzero** [akhenry/openmct-yamcs#464]
#### Summary

This ticket includes 
- [ ] Update github workflow references
- [ ] Update CI references
- [ ] Test with latest `openmct-yamcs`

**Comment by ozyx** [comment]
Building quickstart yamcs 5.9.8 is [currently broken due to runtime error](https://github.com/yamcs/quickstart/issues/29)
