### ISSUE TITLE
Error in plots if parameter has no configured alarms

### ISSUE THREAD

**Issue by shefalijoshi** [akhenry/openmct-yamcs#66]
Go to a parameter plot like `traverseYaw` which has no alarmRange configured in yamcs. You'll see an error in console.
`Uncaught (in promise) TypeError: t is undefined
    getLimitFromAlarmRange openmct-yamcs.js:868
    convertToLimits openmct-yamcs.js:862
    getLimitsForParameter openmct-yamcs.js:859`

**Comment by unlikelyzero** [comment]
Note: Severity:critical

**Comment by shefalijoshi** [comment]
Testing instructions:
Navigate to any telemetry plot view in the VIPER dictionary. You should not see any errors in the console.
Try traverseYaw, angleToYaw, navCamPan

**Comment by charlesh88** [comment]
Verified fixed Testathon 06-25-21

**Comment by nikhilmandlik** [comment]
Verified Fixed.
