### ISSUE TITLE
[Historical Provider] Issues with auto paging

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#67]
Limit requests weren't being respected and creating many requests. Some requests were capped at 1000 arbitrarily.

## Testing
- look at any navCam imagery and make sure there aren't an outrageous amount of reqs in the network tab
- make sure large time span historical requests are making many fetch requests in the network tab
- in the network tab, look for continuation tokens "next=[randomString]", if the limit=1000, or count=1000 in requested url and token is present, make sure other requests follow

**Comment by unlikelyzero** [comment]
Verified by Charles on update

**Comment by unlikelyzero** [comment]
Verified on CDA Testathon
