### ISSUE TITLE
YAMCS search returns unexpected results

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#69]
Searching for YAMCS telemetry points and subsystems returns a number of results that do not contain the search terms I entered. This appears to be because [the parameter search capability in Yamcs searches on name and on Yamcs namespace](https://docs.yamcs.org/yamcs-http-api/mdb/list-parameters/). This is not necessarily a bad thing. eg. if I search for a subsystem, it's also returning the member parameters of that subsystem. This is often useful, however it's not necessarily obvious to the user what's happening.

Not proposing any particular fix for this right now, some design improvements are necessary to improve search generally in Open MCT, and this use case should be considered as part of those discussions.

eg.
In a Yamcs quickstart deployment if I search for "processor" I see the `processor` subsystem returned, but also the `mode` and `name` parameters, which are members of the `mode` subsystem.

![Screen Shot 2021-07-13 at 12 20 57 PM](https://user-images.githubusercontent.com/4215777/125512617-eab5c579-1e49-4e41-85cb-196995fbed82.png)

![Screen Shot 2021-07-13 at 12 21 07 PM](https://user-images.githubusercontent.com/4215777/125512637-daf09347-c6c9-43ca-889e-c1247695e96f.png)

**Comment by unlikelyzero** [comment]
@scottbell can you see if your task to improve search will cover this enhancement?

**Comment by scottbell** [comment]
I think with the way we're doing search now, the namespace/path is part of the search result and (presumably) more obvious. @akhenry should confirm though.

**Comment by akhenry** [comment]
Yeah I think that this can be closed, we are providing contextual search results now. I'll close and mark unverified.

**Comment by akhenry** [comment]
## Testing Instructions
1. Search for "processor"
2. Note that results are provided for the "processor" space system, as well as the "name", and "mode" parameters. (Other matching parameters may also be returned)
3. Verify that "name" and "mode" are now shown with a contextual path that includes the "processor" space system.
4. Verify that any other matches returned include "processor" either in the name of the parameter itself, or in the path to the parameter.

**Comment by davetsay** [comment]
The object search seems to be fixed but annotations search seem to still be showing random results.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/3614296/193895203-70da3807-ba8e-4871-920d-b7ec2defe5c4.png">

**Comment by scottbell** [comment]
@davetsay @akhenry the tag model has been redone. Can you please test with new tags?

**Comment by akhenry** [comment]
Have deleted all annotations in the test environment. It appears that all tagged notebook entries are still appearing in search results irrespective of the search text entered

**Comment by scottbell** [comment]
I’ll take a look and see if I can replicate.

**Comment by scottbell** [comment]
Ah, was able to replicate the issue. Will get a fix and a test in ASAP

**Comment by scottbell** [comment]
To test:

1. Create a notebook, an entry, and a Science tag.
2. Search for "Sc", you should see the Science tag returned
3. Search for "Xq", you should get no search results back

https://user-images.githubusercontent.com/9853862/193990839-3d17eec1-bfea-47b9-ba1e-05840b17d2b5.mov
