### ISSUE TITLE
[Telemetry Provider] Abort requests

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#70]
The yamcs historical telemetry provider needs to be able to abort telemetry requests. This provides a workaround when there are multiple fetches happening for one telemetry request (due to a limitation in yamcs of 1000 results per request).

## Testing
- open the network developer tab to watch XHR requests
- request a telemetry item that has more than 1000 results
- notice multiple requests being made
- navigate away from the telemetry item
- requests should show 'cancelled'
- verify cancelled requests and not further requests for that item (previously, many more requests could be mad)

**Comment by unlikelyzero** [comment]
Will retest with https://github.com/nasa/openmct/pull/3689

**Comment by unlikelyzero** [comment]
Verified fixed
