### ISSUE TITLE
Improve Handling of Aggregates in Open MCT

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#75]
YAMCS supports "Aggregate" parameter types that associate multiple parameter values with a single timestamp. 

eg. here's a screenshot of the YAMCS interface for an aggregate telemetry point (taken from [YAMCS-Quickstart](https://github.com/yamcs/quickstart))

![Screen Shot 2021-08-19 at 4 41 27 PM](https://user-images.githubusercontent.com/4215777/130157913-658366c6-b17e-4216-bbd8-42c17e09b269.png)

Open MCT supports this concept at a platform level, eg. the SineWaveGenerator produces telemetry data objects with both sin and cos attributes associated with a single timestamp. However currently the **Open MCT-YAMCS** telemetry adapters do not. Instead they only support a single "value" attribute per telemetry datum so the telemetry datum objects that they produce look something like this

```JavaScript
{
    id: "~myproject~CCSDS_Packet_Sequence.Count", 
    timestamp: "2021-08-19T23:13:12.812Z",
    value: 39
}
```
So, although the Open MCT-YAMCS plugin does handle YAMCS' aggregate parameter types, but it does so by showing the aggregate parameter as a folder in the tree, and exploding its members out into separate telemetry objects. The same aggregate parameter from the screenshot above is represented in Open MCT like so:

![Screen Shot 2021-08-19 at 4 44 12 PM](https://user-images.githubusercontent.com/4215777/130158050-33085425-2f91-465d-b333-ea64c6929a15.png)

This is fine, but there are cases (such as spectral plots) where it's useful to be able to treat the aggregate as a single telemetry point where each aggregate member is an attribute of the telemetry datum. So, instead of a single value attribute as in the previous example, the resulting telemetry datum might look something like this:

```JavaScript
{
    id: "~myproject~CCSDS_Packet_Sequence", 
    timestamp: "2021-08-19T23:13:12.812Z",
    groupFlags: 3,
    count: 39
}
```

As mentioned previously, Open MCT handles this type of data just fine with the right telemetry metadata (see the Sine Wave Generator as an example).

So I think the right approach for handling Aggregate telemetry types is to:
1. Create a new "aggregate" object type that we will use to represent aggregate parameters. It will be a telemetry point itself (unlike the current folder representation), so views will be able to subscribe to it. eg. if you dragged an aggregate object into a table you would see a column for each of its members. eg. ch1, ch2, ch3, ch4...etc. in the previous above.
2. Modify the Open MCT-YAMCS plugin telemetry metadata so that instead of just "timestamp" and "value", aggregate objects have metadata for all of their members.
3. The available views for an "aggregate" object type should be either the AutoFlowTabular, the LadTable, or both? I'll let @charlesh88 make the final decision. This will allow users to preview telemetry for all of the members of the aggregate without even having to build a display.

Now, here's where it gets really interesting. Aggregate objects should also have composition! They should still expose each of their members as individual telemetry points, just like we currently do! This is for backwards compatibility, but also to give users the option of handling aggregate members individually or all together.

**Comment by merose** [comment]
One complexity is that aggregates in Yamcs can have simple or _aggregate_ members. One example is:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/1649381/130158979-06cba8b4-9506-4e18-aac3-44ac7e9efe0a.png">

I looked through the VIPER telemetry, and I couldn't find an example of an aggregate containing both members that you'd want to plot _along with an aggregate_, but it could happen in general. I guess you could ignore aggregate members for the purpose of plotting or showing in a table, but still show them as children in the object tree.

**Comment by akhenry** [comment]
@merose Ah, good catch, thanks! I think you're right, for now we just ignore the aggregate members when producing telemetry datum objects, but we don't ignore them for the purposes of composition, so they still appear in the tree.

Yikes, I don't know what a general solution would even look like for handling n-deep aggregate member relationships in telemetry views...Our UI really doesn't have any provision for handling groups of related telemetry points. Maybe initially they could produce flattened telemetry datum objects with a union of all of the members of the entire aggregate tree below the subscribed point? I wonder if you might get namespace collisions doing that though...we could probably deal with that though.

I've thought for a while though that we need support for group handling of telemetry points in Open MCT, so maybe this is a good impetus for exploring that. Maybe this could be layered onto the previous suggestion, so that when subscribing to aggregates with aggregate members you get the union of all of the members, but with hints in the UI indicating the aggregate relationships, and provision for handling them as groups (eg. for adding and removing in tables, plots, etc.). The fact that they can potentially be embedded infinitely deep makes this a really tricky UI problem though...

**Comment by unlikelyzero** [comment]
re-opening. 3rd tier data is not showing up

**Comment by charlesh88** [comment]
Verified fixed 12-16-21
