### ISSUE TITLE
[Historical Provider] Provider is mutating options state, which causes incorrect requests

### ISSUE THREAD

**Issue by jvigliotta** [akhenry/openmct-yamcs#84]
When options are passed in, we make updates to them, but we don't copy first, so these updates travel all the way back to the Telemetry Collection request options, this was causing an issue where, sending in no size option, would be set to 1000 on subsequent requests. Need to make a copy of the options object, before making the request in the provider.

**Comment by jvigliotta** [comment]
## Testing
- make telemetry requests in fixed time with network tab open
- make another request after changing the time in the input boxes
- make sure get request start and end time's update appropriately

**Comment by kobe1104** [comment]
The start/end time seems correct. Verified fixed Testathon 9/30/2021.
