### ISSUE TITLE
Use native Date parsing of ISO 8601 dates

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#9]
YAMCS currently provides timestamps as numbers (`generationTime` which is milliseconds since the UNIX epoch, as TAI, which includes 37 additional leap seconds), or as human readable ISO 8601 date strings (generationTimeUTC).

The number format is to be deprecated (although at some point I believe it will be renamed to `generationTime`), and in any case requires client-side handling of leap seconds. Parsing the string version of the date using Open MCT's built in `UTCTimeFormat` is too slow due to the use of a 3rd party library (moment.js). See https://github.com/yamcs/yamcs/issues/409 for some discussion of this.

The best compromise right now is going to be to use the ISO date string, but use native Date parsing instead of using Moment for doing this. 

1. Create a new `ISODateFormat`
2. Implement the `parse` function using `Date.parse()` to parse the string value to a number (MS since UNIX epoch) and return it. Use [UTCTimeFormat](https://github.com/nasa/openmct/blob/master/platform/commonUI/formats/src/UTCTimeFormat.js) as a guide. Include the short circuit logic for values that are already numbers, or undefined.
3. Implement the `format` function using `new Date(value).toISOString()`
4. Implement the `validate` function using `Date.parse(text)` and check if the result is `NaN`. 
6. Modify the [YAMCS object provider](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/object-provider.js) to use the new `ISODateFormat` instead of the `UTCTimeFormat`. This will involve changing the telemetry metadata that is created for each dictionary entry.

**Comment by jvigliotta** [comment]
To test, load up OpenMCT with the openmct-yamcs adapter. Verify that any data coming in has correct timestamps and there are no errors.
