### ISSUE TITLE
The LAD View should be the default view of aggregate telemetry types

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#90]
When a user navigates to an aggregate telemetry type the Plot view is shown, with the first aggregate parameter attribute plotted and the option to switch to others.

Instead it would be more useful to display the current value of all aggregate parameter attributes. The LAD table does this, so the simple answer is to make the LAD Table the default view for aggregate telemetry parameters.

My suggestion for now is that we make the LAD Table View available for all objects that produce telemetry _and_ have children.

[The `canView` function](https://github.com/nasa/openmct/blob/4d8db8eb7c474dec50dde12500118739ce22c1de/src/plugins/LADTable/LADTableViewProvider.js#L33) is called to determine whether a given view applies to a given object. From here you could call [`openmct.telemetry.isTelemetryObject(domainObject)`](https://github.com/nasa/openmct/blob/master/src/api/telemetry/TelemetryAPI.js#L168) to determine whether the given object can provide telemetry, and you could use <pre>[openmct.composition.get(domainObject)](https://github.com/nasa/openmct/blob/4d8db8eb7c474dec50dde12500118739ce22c1de/src/api/composition/CompositionAPI.js#L72) !== undefined </pre> to determine whether the object supports composition (ie. that it _can_ contain children). To check whether it actually does have children requires an asynchronous call, and unfortunately `canView` is synchronous.

**Comment by michaelrogers** [comment]
Testing Instructions:

1. Click on an data type in the tree that has aggregate telemetry. 
 E.g. ViperRover/GroundTruth/pose
2. Observe that the LAD Table is the default type

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/13/2021 (but... i kinda helped on it a bit, so SOMEONE ELSE CHECK AS WELL... please)

**Comment by charlesh88** [comment]
Verified fixed 12-16-21
