### ISSUE TITLE
Add user provider to expose logged in user

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#92]
Yamcs provides information about the logged in user through the `/api/user` endpoint. It will return data that looks something like this:
```
{
  "superuser": false,
  "creationTime": "2021-12-16T16:41:15.103Z",
  "lastLoginTime": "2021-12-16T18:59:30.635Z",
  "active": true,
  "name": "user",
  "confirmationTime": "2021-12-16T16:41:15.103Z"
}
```

This can be used to define a user provider for the new User API that returns the logged in user's name.

**Comment by jvigliotta** [comment]
## Testing
- verify you see your NDC username
