### ISSUE TITLE
Support Yamcs units in Open MCT displays

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#93]
XTCE allows units to be defined, and these are returned [by the Yamcs API](https://docs.yamcs.org/yamcs-http-api/mdb/list-parameters/) on parameter queries (ie. when we build the tree). 

Open MCT [also supports units in telemetry metadata](https://github.com/nasa/openmct/blob/master/API.md#telemetry-metadata) and in our views, so we should expose XTCE-defined units as Open MCT telemetry metadata so that our displays can show them.

**Comment by akhenry** [comment]
## Testing Notes
Verify that units are appearing in the Open MCT views that support them. Namely:
* Plot legends
* Telemetry Tables
* Display Layouts (alphanumeric telemetry views)

**Comment by davetsay** [comment]
For aggregates, units are displayed in LAD tables, but they are not displayed in telemetry tables, plots, nor plot legends.

**Comment by ozyx** [comment]
Verified Testathon 7/6/22
