### ISSUE TITLE
npm start does not work after addition of user provider

### ISSUE THREAD

**Issue by merose** [akhenry/openmct-yamcs#96]
Just cloned latest version (commit adb6ab543e, date 2022–01–20). After running `npm install` and `npm start`, I get this error in the Javascript console:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1649381/151445251-e0da6df8-8395-487d-b8cf-eb803553eee0.png">

Environment:
- OS X 11.6.3
- Chrome 97.0
- node.js v16.3.2

**Comment by merose** [comment]
Also, minor nit: the URL that starts in the browser has a double slash: `localhost:9000//example/index.html`

**Comment by jvigliotta** [comment]
These issues have been fixed by: https://github.com/akhenry/openmct-yamcs/pull/118
